### ISSUE TITLE
Draw function and game loop optimisation

### ISSUE THREAD

**Issue by MatthewPageUK** [Perrytheplatypus43/Mozilla-Thimble-Catch-the-Bricks-Looking-For-Help#1]
The draw() function appears to pause the game for every redraw, pausing and resuming also changes the button textContent every single frame. This is probably undesirable. I would suggest letting the animationFrame run constantly and use the running variables to control what happens..

**Comment by Perrytheplatypus43** [comment]
I have tried this before and something was going wrong and the only way I could have fixed it was pausing it but feel free to create a pull request with the optimization so we can test it.

**Comment by Perrytheplatypus43** [comment]
Okay, I just tested it and it seems to work fine.

**Comment by Perrytheplatypus43** [comment]
@MatthewPageUK can you take a look at the pull request and make sure that is what you were suggesting.
