### ISSUE TITLE
Doesn't work on mobile browser

### ISSUE THREAD

**Issue by ConradP** [Perrytheplatypus43/Mozilla-Thimble-Catch-the-Bricks-Looking-For-Help#14]
Can't control the game with touchscreen

**Comment by ConradP** [comment]
Attaching left and right control to the mousemove as well as the keyboard would allow for control on mobile browser

**Comment by Perrytheplatypus43** [comment]
Have you tried by moving by touching the half of the screen you want to move towards?

**Comment by ConradP** [comment]
Ah, I didn't realize it was moved by tapping rather than by touch.
I guess it does work.
